### ISSUE TITLE
Requests error triggers an exception that is not caught

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/kernel-crawler#75]
**Describe the bug**

https://prow.falco.org/view/s3/falco-prow-logs/logs/update-kernels/1599644916609191936
```
 During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/kernel-crawler", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/kernel_crawler/main.py", line 56, in crawl
    res = crawl_kernels(distro, version, arch, image, out_fmt == 'driverkit')
  File "/usr/local/lib/python3.10/site-packages/kernel_crawler/crawler.py", line 89, in crawl_kernels
    res = d.get_package_tree(version)
  File "/usr/local/lib/python3.10/site-packages/kernel_crawler/repo.py", line 43, in get_package_tree
    repos = self.list_repos()
  File "/usr/local/lib/python3.10/site-packages/kernel_crawler/flatcar.py", line 51, in list_repos
    repos.extend(self.scan_repo(repo))
  File "/usr/local/lib/python3.10/site-packages/kernel_crawler/flatcar.py", line 36, in scan_repo
    dists = requests.get(base_url)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 
```

**How to reproduce it**

Happens sometimes.

**Expected behaviour**

Even if not a good practice, we might want to just skip  the current distro if any exception happens, in the `crawl_kernels` loop.
We can have multiple type of exceptions:
* `requests.get()` generated
* `raise_for_status()` generated
* plus many more

And i don't think we want to deal with every of them.

**Comment by FedeDP** [comment]
CC @EXONER4TED

**Comment by FedeDP** [comment]
We can close this one.
/close
